// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using loggyAPI.Data;

namespace loggyAPI.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190915111012_loggyAPI.DATA.DataContext")]
    partial class loggyAPIDATADataContext
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("loggyAPI.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PasswordSalt");

                    b.Property<int?>("RoleFk");

                    b.Property<string>("Token");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.HasIndex("RoleFk")
                        .IsUnique()
                        .HasFilter("[RoleFk] IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("loggyAPI.Data.Entities.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Role");

                    b.HasKey("Id");

                    b.ToTable("UsersRole");
                });

            modelBuilder.Entity("loggyAPI.Data.Entities.User", b =>
                {
                    b.HasOne("loggyAPI.Data.Entities.UserRole", "Role")
                        .WithOne("User")
                        .HasForeignKey("loggyAPI.Data.Entities.User", "RoleFk");
                });
#pragma warning restore 612, 618
        }
    }
}
